name: auth
description: "A secure and elegant authentication app built with Flutter, supporting TOTP/HOTP and biometrics."
publish_to: 'none'
version: 0.1.0+10

environment:
  sdk: ^3.9.0

dependencies:
  # Core & Internationalization
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  # State Management & Hooks
  flutter_hooks: 0.21.3+1
  flutter_riverpod: 3.1.0
  hooks_riverpod: 3.1.0
  riverpod_annotation: 4.0.0

  # Navigation
  go_router: 17.0.1

  # Database & Persistence
  drift: 2.30.1
  drift_flutter: 0.2.8
  shared_preferences: 2.5.4
  sqlite3_flutter_libs: 0.5.41

  # UI & Styling
  dynamic_color: 1.8.1
  flutter_svg: 2.2.3
  flutter_swipe_action_cell: 3.1.6

  # Security & Cryptography
  base32: 2.2.0
  crypto: 3.0.7
  encrypt: 5.0.3
  hashlib: 2.3.0

  # Utilities & System
  file_selector: 1.1.0
  mobile_scanner: 7.1.4
  path: 1.9.1
  path_provider: 2.1.5

dev_dependencies:
  # Testing & Linting
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: 2.10.5
  drift_dev: 2.30.1
  riverpod_generator: 4.0.0+1

  # Tools
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/

  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf